spring:
  application:
    name: vorix-auth-service

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate

    show-sql: false

  flyway:
    enabled: true
    locations: classpath:db/migration

  mail:
    host: smtp.gmail.com
    port: 587
    username: YOUR_RESPECTIVE_GMAIL
    password: YOUR_RESPECTIVE_GMAIL_APP_PASSWORD

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8081

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: 900000         # 15 minutes in milliseconds
  refresh-token-expiration: 604800000     # 7 days in milliseconds

app:
  frontend-url: http://localhost:3001

security:
  password-reset-token-expiration: 900000           # 15 minutes in milliseconds
  email-verification-token-expiration: 86400000     # 24 hours in milliseconds