ALTER TABLE users
ADD COLUMN provider VARCHAR(30) NOT NULL DEFAULT 'LOCAL';

ALTER TABLE users
ADD COLUMN provider_id VARCHAR(255);

ALTER TABLE users
ADD COLUMN email_verified BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE users
ADD COLUMN active BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE users
ADD COLUMN account_locked BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE users
ADD COLUMN failed_login_attempts INTEGER NOT NULL DEFAULT 0;

ALTER TABLE users
ADD COLUMN last_login_at TIMESTAMP;

ALTER TABLE users
ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT FALSE;