ALTER TABLE connected_repositories
ADD COLUMN full_name VARCHAR(255) NOT NULL,
ADD COLUMN is_private BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN visibility VARCHAR(20),
ADD COLUMN archived BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN disabled BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN clone_url VARCHAR(500),
ADD COLUMN html_url VARCHAR(500),
ADD COLUMN primary_language VARCHAR(100),
ADD COLUMN github_created_at TIMESTAMPTZ,
ADD COLUMN github_updated_at TIMESTAMPTZ;